spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/


zuul:
  prefix: /api
#  ignored-services: review-service
  routes:
    review-service:
      path: /client/**